language: node_js
node_js:
- '10'

# 生成私钥
before_install:
- openssl aes-256-cbc -K $encrypted_5cab76ca3150_key -iv $encrypted_5cab76ca3150_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

# 改变文件权限
 - chmod 600 ~/.ssh/id_rsa

 # 配置 ssh
 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa

# 运行脚本
script: npm run deploy
